name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Generate gradlew
      run: gradle wrapper --gradle-version 8.6

    - name: Generate launcher icons
      run: |
        sudo apt-get install -y imagemagick
        mkdir -p app/src/main/res/mipmap-mdpi
        mkdir -p app/src/main/res/mipmap-hdpi
        mkdir -p app/src/main/res/mipmap-xhdpi
        mkdir -p app/src/main/res/mipmap-xxhdpi
        mkdir -p app/src/main/res/mipmap-xxxhdpi
        convert app/src/main/res/logo_cv.png -resize 48x48 app/src/main/res/mipmap-mdpi/ic_launcher.png
        convert app/src/main/res/logo_cv.png -resize 72x72 app/src/main/res/mipmap-hdpi/ic_launcher.png
        convert app/src/main/res/logo_cv.png -resize 96x96 app/src/main/res/mipmap-xhdpi/ic_launcher.png
        convert app/src/main/res/logo_cv.png -resize 144x144 app/src/main/res/mipmap-xxhdpi/ic_launcher.png
        convert app/src/main/res/logo_cv.png -resize 192x192 app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
        cp app/src/main/res/mipmap-mdpi/ic_launcher.png app/src/main/res/mipmap-mdpi/ic_launcher_round.png
        cp app/src/main/res/mipmap-hdpi/ic_launcher.png app/src/main/res/mipmap-hdpi/ic_launcher_round.png
        cp app/src/main/res/mipmap-xhdpi/ic_launcher.png app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
        cp app/src/main/res/mipmap-xxhdpi/ic_launcher.png app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
        cp app/src/main/res/mipmap-xxxhdpi/ic_launcher.png app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png

    - name: Generate Keystore
      run: |
        keytool -genkeypair -v \
          -keystore chefvision.keystore \
          -alias chefvision \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass 'ChefVision2026$' \
          -keypass 'ChefVision2026$' \
          -dname "CN=Gustavo Garay, OU=Altea-Garay, O=Altea-Garay, L=Garcia, S=NuevoLeon, C=MX"

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Sign APK
      run: |
        apksigner sign \
          --ks chefvision.keystore \
          --ks-pass pass:'ChefVision2026$' \
          --key-pass pass:'ChefVision2026$' \
          --ks-key-alias chefvision \
          --out app/build/outputs/apk/release/ChefVisionIA-signed.apk \
          app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ChefVisionIA-release
        path: app/build/outputs/apk/release/ChefVisionIA-signed.apk
